name: Build and Upload Artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      # 'myuser' can be any string. It is used to name the Docker image. It doesn't have to be your DockerHub username
      # because we are not pushing the image to DockerHub.
      uses: docker/build-push-action@v2
      with:
        context: .devcontainer
        push: false
        tags: appac/pico-build:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Run build in Docker container
      run: |
        docker run --name pico-build-container -v "${{ github.workspace }}:/workspace" -w /workspace/build appac/pico-build:latest make

    - name: Copy uf2 file from Docker container
      run: docker cp pico-build-container:/workspace/build/hello_world.uf2 .

    - name: Upload uf2 file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: hello_world.uf2
        path: hello_world.uf2
