name: Build and Upload Artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Run Docker Image
        run: |
          docker buildx create --use
          docker buildx build --provenance=false --load --progress=plain --file .devcontainer/Dockerfile --tag pico-build:latest --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max .
          mkdir -p build
          docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace/build pico-build:latest cmake .. -DPICO_BOARD=pico_w
          docker run --name pico-build-container -v "${{ github.workspace }}:/workspace" -w /workspace/build pico-build:latest make

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Upload uf2 file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello_world.uf2
          path: build/hello_world.uf2
